# Generated by Django 5.2.6 on 2025-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='savings',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
