# Generated by Django 5.2.5 on 2025-09-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_payment_payment_method_savings_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
