# Generated by Django 6.0.3 on 2026-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0005_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password Reset'), ('account_creation', 'Account Creation')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
